# Generated by Django 5.2.4 on 2025-07-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_detallereserva_monto_alter_detallereserva_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta de débito', 'Tarjeta de débito'), ('Tarjeta de crédito', 'Tarjeta de crédito'), ('Yape/Plin', 'Yape/Plin')], max_length=50),
        ),
    ]
