# Generated by Django 5.2.4 on 2025-07-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_reserva_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('en_curso', 'En curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No asistió')], default='confirmada', max_length=20),
        ),
    ]
