# Generated by Django 5.2.1 on 2025-07-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField()),
                ('ubicacion', models.CharField(choices=[('Piso1', 'Piso1'), ('Piso2', 'Piso2'), ('Terraza', 'Terraza')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Fondo', 'Fondo'), ('Bebida', 'Bebida'), ('Postre', 'Postre')], max_length=50)),
            ],
        ),
    ]
